[package]
name = "pinex"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pinex-proto.workspace = true
pinex-device = { workspace = true, features = ["sim"] }
pinex-input.workspace = true
pinex-ui.workspace = true

[dev-dependencies]
pinex-device = { workspace = true, features = ["sim"] }
